<?php if (isset($_SESSION['login']) && isset($_SESSION['login']['admin']) && $_SESSION['login']['admin']==1) : ?>
<form method="post" action="<?= $router->pathFor('inscription') ?>">
    <div class="modal-dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title">Inscription d'un participant</h3>
                </div>

                <div class="modal-body">
                    <!-- Formulaire inscription -->
                    <div class="form-group">
                        <label for="user">Nom d'utilisateur</label>
                        <input required type="text" name="user" maxlength="30" class="form-control"
                               placeholder="Benoit54">
                    </div>
                    <div class="form-group">
                        <label for="password">Mot de passe</label>
                        <div class="input-group">
                            <input required type="password" name="password" maxlength="30" class="form-control"
                                   placeholder="" id="password">
                            <div class="input-group-append">
                                <button class="input-group-text" onclick="toggleVisibility('password')" type="button"
                                        style="outline: none" tabindex="-1"><i class="fas fa-eye"></i></button>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input required type="email" name="email" maxlength="30" class="form-control"
                               placeholder="benoit@orange.fr">
                    </div>
                    <div class="form-group">
                        <label for="nom">Nom</label>
                        <input required type="text" name="nom" maxlength="30" class="form-control" placeholder="Domont">
                    </div>
                    <div class="form-group">
                        <label for="prenom">Prénom</label>
                        <input required type="text" name="prenom" maxlength="30" class="form-control"
                               placeholder="Benoit">
                    </div>
                </div>

                <div class="modal-footer">
                    <a class="btn btn-secondary" href="<?= $rootUri ?>" role="button">Annuler</a>
                    <button type="submit" class="btn btn-success">Inscription</button>
                </div>
            </div>
        </div>
    </div>
</form>

<?php else: ?>
       <h5 align="center"> <strong>Il faut être connecté et être administrateur pour creer un compte.</strong></h5>
<?php endif; ?>

<script>
    function toggleVisibility(input) {
        input = document.getElementById(input);
        input.nextElementSibling.firstElementChild.firstElementChild.classList.toggle("fa-eye-slash");
        input.nextElementSibling.firstElementChild.firstElementChild.classList.toggle("fa-eye");
        if (input.type === 'password') {
            input.type = 'text';
        } else {
            input.type = 'password';
        }
    }
</script>