<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script>document.getElementsByTagName("html")[0].className += " js";</script>
    <link rel="icon" href="<?= $rootUri ?>/public/images/img_site.png" type="image/png" sizes="16x16">
    <link rel="stylesheet" href="<?= $rootUri ?>/public/css/planningStyle.css">
    <link rel="stylesheet" href="<?= $rootUri ?>/public/css/bootstrap.css">
    <link rel="stylesheet" href="<?= $rootUri ?>/public/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.1.0/css/all.css"/>
    <title><?=$title?></title>
</head>
<body>
<script src="<?= $rootUri ?>/public/js/jquery.slim.min.js"></script>
<script src="<?= $rootUri ?>/public/js/bootstrap.min.js"></script>


<nav id="nav" class="navbar navbar-expand-lg navbar-dark sticky-top headfoot ">
    <div class="container">
        <a href="<?= $router->pathFor('planning',['semaine' => 'A']) ?>"><img src="<?= $rootUri ?>/public/images/logo.svg" width="50" height="50"></a>
        <a class="navbar-brand pl-3" href="<?= $router->pathFor('planning',['semaine' => 'A']) ?>">Grande Epicerie General</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="<?php
                    if (isset($_SESSION['login']))
                        echo $router->pathFor('planning',['semaine' => 'A']);
                    else
                        echo $router->pathFor('login');
                    ?>">Accueil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $router->pathFor('planning',['semaine' => 'A']) ?>">Planning</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $router->pathFor('newCreneau') ?>">Nouveau Créneau</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $router->pathFor('members') ?>">Membres</a>
                </li>
            </ul>
        </div>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <?php if (isset($_SESSION['login'])) : ?>
                    <li class="nav-item">
                        <a class="nav-link logout" href="<?=$router->pathFor('logout')?>">Déconnexion</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?=$router->pathFor('account')?>">Mon compte</a>
                    </li>
                    <?php if ( isset($_SESSION['login']['admin']) and $_SESSION['login']['admin']==1) : ?>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Gestion des comptes
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" >Gestion des comptes</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="<?=$router->pathFor('inscription')?>">Inscription d'un membre</a>
                            <a class="dropdown-item" href="<?=$router->pathFor('gestion')?>">Modification d'un membre</a>
                        </div>
                    </li>
                    <?php endif; ?>
                <?php else : ?>
                    <li class="nav-item">
                        <a class="nav-link" href="<?=$router->pathFor('login')?>">Connexion</a>
                    </li>
                <?php endif; ?>

            </ul>
        </div>
    </div>
</nav>

    <div class="container mt-3">
        <?= $content ?>
    </div>
    <br>
</body>


<footer class="page-footer font-small mdb-color lighten-3 pt-4 colorfoot ">
    <div class="container text-center text-md-left">
        <div class="row">
            <div class="col-md-4 col-lg-3 mr-auto my-md-4 my-0 mt-4 mb-1">
                <h5 class="font-weight-bold text-uppercase mb-4"><i class="fas fa-envelope mr-3"></i>EMAIL</h5>
                <p>contact@grandeepiceriegenerale.fr</p>
            </div>
            <hr class="clearfix w-100 d-md-none">
            <div class="col-md-4 col-lg-3 mr-auto my-md-4 my-0 mt-4 mb-1">
                <h5 class="font-weight-bold text-uppercase mb-4"><i class="fas fa-home mr-3"></i>ADRESSE</h5>
                <p>61 Rue Saint-Nicolas, 54000 Nancy</p>
            </div>

            <div class="col-md-4 col-lg-3 mx-auto my-md-4 my-0 mt-4 mb-1">
                <h5 class="font-weight-bold text-uppercase mb-4">TWITTER</h5>
                <p ><!-- Twitter -->
                    <a type="button" href="https://twitter.com/GEGNancy" target="_blank"><img
                                src="<?= $rootUri ?>/public/images/twitter.png" type="image/png" height="32" width="32"
                                style="margin-right: 10px">@GEGNancy</a></p>
            </div>
            <hr class="clearfix w-100 d-md-none">
            <div class="col-md-2 col-lg-2 text-center mx-auto my-4">
                <h5 class="font-weight-bold text-uppercase mb-4">FACEBOOK</h5>
                <p><!-- Facebook -->
                    <a type="button" href="https://www.facebook.com/GEGNancy/" target="_blank"><img
                                src="<?= $rootUri ?>/public/images/facebook.png" type="image/png" height="32" width="32"
                                style="margin-right: 10px">@GEGNancy</a></p>




            </div>
        </div>
    </div>
    <div class="footer-copyright text-center py-3 headfoot">La Grande Épicerie Générale © tout droit reservé</div>
</footer>


</html>