<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="<?= $rootUri ?>/public/images/img_site.png" type="image/png" sizes="16x16">
    <link rel="stylesheet" href="<?= $rootUri ?>/public/css/bootstrap.css">
    <link rel="stylesheet" href="<?= $rootUri ?>/public/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.1.0/css/all.css"/>
    <title><?=$title?></title>
</head>

<nav class="navbar navbar-expand-lg navbar-dark sticky-top headfoot">
    <div class="container">
        <a class="navbar-brand" href="<?= $router->pathFor('home') ?>">Grande Epicerie General</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link"">Accueil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" ">Page 1</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" ">Page 2</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" ">Page 3</a>
                </li>
            </ul>
        </div>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <?php if (isset($_SESSION['login'])) : ?>
                    <li class="nav-item">
                        <a class="nav-link logout" ">Déconnexion</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" ">Mon compte</a>
                    </li>
                <?php else : ?>
                    <li class="nav-item">
                        <a class="nav-link" ">Inscription</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" ">Connexion</a>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
</nav>


<div class="container mt-3">
    <?= $content ?>
</div>
<br>

<footer class="page-footer font-small teal pt-4 headfoot">
    <div class="container-fluid text-center text-md-left">
        <div class="row">
            <div class="col-md-6 mt-md-0 mt-3">
                <h5 class="text-uppercase font-weight-bold">Footer text 1</h5>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Expedita sapiente sint, nulla, nihil
                    repudiandae commodi voluptatibus corrupti animi sequi aliquid magnam debitis, maxime quam recusandae
                    harum esse fugiat. Itaque, culpa?</p>
            </div>
            <hr class="clearfix w-100 d-md-none pb-3">
            <div class="col-md-6 mb-md-0 mb-3">
                <h5 class="text-uppercase font-weight-bold">Footer text 2</h5>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Optio deserunt fuga perferendis modi earum
                    commodi aperiam temporibus quod nulla nesciunt aliquid debitis ullam omnis quos ipsam, aspernatur id
                    excepturi hic.</p>
            </div>
        </div>
    </div>
    <div class="footer-copyright text-center py-3">Grande Epicerie general © tout droit reservé</div>
</footer>


</html>