<?php if (!isset($_SESSION['login'])) : ?>
    <form method="post" action="<?= $router->pathFor('login') ?>">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="modal-title">Connexion</h3>
                    </div>
                    <div class="modal-body">
                        <?php if (isset($_SESSION['redirect']['msg'])) {
                            echo $_SESSION['redirect']['msg'];
                            unset($_SESSION['redirect']['msg']);
                        } ?>
                        <div class="form-group">
                            <label for="id">Email ou nom d'utilisateur</label>
                            <?php if (isset($_SESSION['redirect']['username'])) {
                                $id = $_SESSION['redirect']['username'];
                                unset($_SESSION['redirect']['username']);
                            } ?>
                            <input required type="text" name="id" maxlength="100" class="form-control" placeholder="Email ou nom d'utilisateur" id="id" <?= isset($id) ? 'value='.htmlspecialchars($id) : 'autofocus'?>>
                            <div class="invalid-feedback" id="idErr">Invalide</div>
                        </div>
                        <div class="form-group mb-0">
                            <label for="password">Mot de passe</label>
                            <div class="input-group">
                                <input required type="password" name="password" maxlength="50" class="form-control" placeholder="Mot de passe" id="password">
                                <div class="input-group-append">
                                    <button class="input-group-text" onclick="toggleVisibility('password')" type="button" style="outline: none" tabindex="-1"><i class="fas fa-eye"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <a class="btn btn-secondary" href="#" role="button">Annuler</a>
                        <button type="submit" class="btn btn-success">Connexion</button>
                    </div>
                </div>
            </div>
    </form>
<?php else: ?>
    <h1>Vous êtes déjà connecté. Cette page n'est pas disponible.</h1>
    <h4>Si vous voulez vous connecter avec un autre compte, déconnectez vous auparavant.</h4>
<?php endif; ?>

<script>
    function toggleVisibility(input) {
        input = document.getElementById(input);
        input.nextElementSibling.firstElementChild.firstElementChild.classList.toggle("fa-eye-slash");
        input.nextElementSibling.firstElementChild.firstElementChild.classList.toggle("fa-eye");
        if (input.type === 'password') {
            input.type = 'text';
        } else {
            input.type = 'password';
        }
    }
</script>
