<div class="jumbotron text-center">
    <h3 class="titre">Membres de La Grande Épicerie Générale</h3>
</div>

<table class="table table-responsive table-center">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Nom</th>
        <th scope="col">Prénom</th>
        <th scope="col">Email</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($accounts as $account) : ?>
        <tr>
            <td scope="row"><?= $account->nom ?></td>
            <td scope="row"><?= $account->prenom ?></td>
            <td scope="row"><?= $account->email ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
