<h1>Créez un nouveau créneau</h1><br>
<form method="POST" action="<?= $router->pathFor('newCreneau') ?>">
    <div class="form-group">
        <label for="cycle">Indiquez le cycle</label>
        <input required type="number" min="0" value="0" placeholder="0" name="cycle" class="form-control" id="cycle">
    </div>
    <div class="form-group">
        <label for="semaine">Indiquez la semaine (A-B-C-D)</label>
        <select id="semaine" name="semaine">
            <option value="a" selected>A</option>
            <option value="b">B</option>
            <option value="c">C</option>
            <option value="d">D</option>
        </select>
    </div>
    <div class="form-group">
        <label for="jour">Indiquez le jour</label>
        <select id="jour" name="jour">
            <option value="1" selected>Lundi</option>
            <option value="2">Mardi</option>
            <option value="3">Mercredi</option>
            <option value="4">Jeudi</option>
            <option value="5">Vendredi</option>
            <option value="6">Samedi</option>
            <option value="7">Dimanche</option>
        </select>
    </div>
    <div class="form-group">
        <label for="heureDeb">Heure de début :</label>
        <select id="heureDeb" name="heureDeb">
            <option value="5">5:00</option>
            <option value="6">6:00</option>
            <option value="7">7:00</option>
            <option value="8" selected>8:00</option>
            <option value="9">9:00</option>
            <option value="10">10:00</option>
            <option value="11">11:00</option>
            <option value="12">12:00</option>
            <option value="13">13:00</option>
            <option value="14">14:00</option>
            <option value="15">15:00</option>
            <option value="16">16:00</option>
            <option value="17">17:00</option>
            <option value="18">18:00</option>
            <option value="19">19:00</option>
            <option value="20">20:00</option>
            <option value="21">21:00</option>
            <option value="22">22:00</option>
            <option value="23">23:00</option>
        </select>
    </div>
    <div class="form-group">
        <label for="heureFin">Heure de début :</label>
        <select id="heureFin" name="heureFin">
            <option value="5">5:00</option>
            <option value="6">6:00</option>
            <option value="7">7:00</option>
            <option value="8">8:00</option>
            <option value="9">9:00</option>
            <option value="10">10:00</option>
            <option value="11" selected>11:00</option>
            <option value="12">12:00</option>
            <option value="13">13:00</option>
            <option value="14">14:00</option>
            <option value="15">15:00</option>
            <option value="16">16:00</option>
            <option value="17">17:00</option>
            <option value="18">18:00</option>
            <option value="19">19:00</option>
            <option value="20">20:00</option>
            <option value="21">21:00</option>
            <option value="22">22:00</option>
            <option value="23">23:00</option>
        </select>
    </div>
    <?php foreach ($roles as $role) : ?>
        <div class="form-group">
            <label for="<?=$role->libelle?>"><?=$role->libelle?></label>
            <input required type="number" min="0" max="50" value="0" placeholder="0" name="<?=$role->libelle?>" class="form-control" id="<?=$role->libelle?>">
        </div>
    <?php endforeach; ?>
    <div class="modal-footer">
        <a class="btn btn-secondary" href="<?= $router->pathFor('planning',['semaine'=>'A']) ?>" role="button">Annuler</a>
        <button type="submit" class="btn btn-primary">Créer le créneau</button>
    </div>
</form>