<div>
  <header class="cd-main-header text-center flex flex-column flex-center">
      <?php if (isset($_SESSION['login'])) : ?>
        <h1 class="text-xl">Bienvenue <?= $_SESSION['login']['prenom']?> <?= $_SESSION['login']['nom']?> !</h1>
      <?php endif; ?>
      <h5>Cycle : 0 - Semaine :</h5>
  </header>

    <nav aria-label="Page navigation example">
        <ul class="justify-content-center pagination">
            <li class="page-item">
                <a class="page-link" href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
            <li class="page-item"><a class="page-link" href="<?= $router->pathFor('planning',['semaine' => 'A']) ?>">A</a></li>
            <li class="page-item"><a class="page-link" href="<?= $router->pathFor('planning',['semaine' => 'B']) ?>">B</a></li>
            <li class="page-item"><a class="page-link" href="<?= $router->pathFor('planning',['semaine' => 'C']) ?>">C</a></li>
            <li class="page-item"><a class="page-link" href="<?= $router->pathFor('planning',['semaine' => 'D']) ?> ">D</a></li>
            <li class="page-item">
                <a class="page-link" href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        </ul>
    </nav>

  <div class="cd-schedule cd-schedule--loading margin-top-lg margin-bottom-lg js-cd-schedule">
    <div class="cd-schedule__timeline">
      <ul>
        <li><span>05:00</span></li>
        <li><span>06:00</span></li>
        <li><span>07:00</span></li>
        <li><span>08:00</span></li>
        <li><span>09:00</span></li>
        <li><span>10:00</span></li>
        <li><span>11:00</span></li>
        <li><span>12:00</span></li>
        <li><span>13:00</span></li>
        <li><span>14:00</span></li>
        <li><span>15:00</span></li>
        <li><span>16:00</span></li>
        <li><span>17:00</span></li>
        <li><span>18:00</span></li>
        <li><span>19:00</span></li>
        <li><span>20:00</span></li>
        <li><span>21:00</span></li>
        <li><span>22:00</span></li>
        <li><span>23:00</span></li>
      </ul>
    </div> <!-- .cd-schedule__timeline -->

    <div class="cd-schedule__events">
      <ul>
        <li class="cd-schedule__group">
          <div class="cd-schedule__top-info"><span>Lundi</span></div>
          <ul>

              <?php foreach ($lundis as $creneau) : ?>
                  <li class="cd-schedule__event">
                      <a data-start="<?= $creneau->heureD ?>:00" data-end="<?= $creneau->heureF ?>:00" data-content="<?= $creneau->id ?>" data-event="event-1" href="#0">
                          <em class="cd-schedule__name" style="display: none"></em>
                      </a>
                  </li>
              <?php endforeach; ?>

              </a>
            </li>
          </ul>
        </li>

          <li class="cd-schedule__group">
              <div class="cd-schedule__top-info"><span>Mardi</span></div>
              <ul>

                  <?php foreach ($mardis as $creneau) : ?>
                      <li class="cd-schedule__event">
                          <a data-start="<?= $creneau->heureD ?>:00" data-end="<?= $creneau->heureF ?>:00" data-content="<?= $creneau->id ?>" data-event="event-1" href="#0">
                              <em class="cd-schedule__name" style="display: none"></em>
                          </a>
                      </li>
                  <?php endforeach; ?>

                  </a>
                  </li>
              </ul>
          </li>
          <li class="cd-schedule__group">
              <div class="cd-schedule__top-info"><span>Mercredi</span></div>
              <ul>

                  <?php foreach ($mercredis as $creneau) : ?>
                      <li class="cd-schedule__event">
                          <a data-start="<?= $creneau->heureD ?>:00" data-end="<?= $creneau->heureF ?>:00" data-content="<?= $creneau->id ?>" data-event="event-1" href="#0">
                              <em class="cd-schedule__name" style="display: none"></em>
                          </a>
                      </li>
                  <?php endforeach; ?>

                  </a>
                  </li>
              </ul>
          </li>

          <li class="cd-schedule__group">
              <div class="cd-schedule__top-info"><span>Jeudi</span></div>
              <ul>

                  <?php foreach ($jeudis as $creneau) : ?>
                      <li class="cd-schedule__event">
                          <a data-start="<?= $creneau->heureD ?>:00" data-end="<?= $creneau->heureF ?>:00" data-content="<?= $creneau->id ?>" data-event="event-1" href="#0">
                              <em class="cd-schedule__name" style="display: none"></em>
                          </a>
                      </li>
                  <?php endforeach; ?>

                  </a>
                  </li>
              </ul>
          </li>

          <li class="cd-schedule__group">
              <div class="cd-schedule__top-info"><span>Vendredi</span></div>
              <ul>

                  <?php foreach ($vendredis as $creneau) : ?>
                      <li class="cd-schedule__event">
                          <a data-start="<?= $creneau->heureD ?>:00" data-end="<?= $creneau->heureF ?>:00" data-content="<?= $creneau->id ?>" data-event="event-1" href="#0">
                              <em class="cd-schedule__name" style="display: none"></em>
                          </a>
                      </li>
                  <?php endforeach; ?>

                  </a>
                  </li>
              </ul>
          </li>

          <li class="cd-schedule__group">
              <div class="cd-schedule__top-info"><span>Samedi</span></div>
              <ul>

                  <?php foreach ($samedis as $creneau) : ?>
                      <li class="cd-schedule__event">
                          <a data-start="<?= $creneau->heureD ?>:00" data-end="<?= $creneau->heureF ?>:00" data-content="<?= $creneau->id ?>" data-event="event-1" href="#0">
                              <em class="cd-schedule__name" style="display: none"></em>
                          </a>
                      </li>
                  <?php endforeach; ?>

                  </a>
                  </li>
              </ul>
          </li>

          <li class="cd-schedule__group">
              <div class="cd-schedule__top-info"><span>Dimanche</span></div>
              <ul>

                  <?php foreach ($dimanches as $creneau) : ?>
                      <li class="cd-schedule__event">
                          <a data-start="<?= $creneau->heureD ?>:00" data-end="<?= $creneau->heureF ?>:00" data-content="<?= $creneau->id ?>" data-event="event-1" href="#0">
                              <em class="cd-schedule__name" style="display: none"></em>
                          </a>
                      </li>
                  <?php endforeach; ?>

                  </a>
                  </li>
              </ul>
          </li>

      </ul>
    </div>

    <div class="cd-schedule-modal">
      <header class="cd-schedule-modal__header">
        <div class="cd-schedule-modal__content">
          <span class="cd-schedule-modal__date"></span>
          <h3 class="cd-schedule-modal__name"></h3>
        </div>

        <div class="cd-schedule-modal__header-bg"></div>
      </header>

      <div class="cd-schedule-modal__body">
        <div class="cd-schedule-modal__event-info" id="cd-schedule-modal__event-info"></div>
        <div class="cd-schedule-modal__body-bg"></div>
      </div>

      <a href="#0" class="cd-schedule-modal__close text-replace">Close</a>
    </div>

    <div class="cd-schedule__cover-layer"></div>
  </div> <!-- .cd-schedule -->

  <script src="<?= $rootUri ?>/public/js/utilPlanning.js"></script> <!-- util functions included in the CodyHouse framework -->
  <script src="<?= $rootUri ?>/public/js/mainPlanning.js"></script>
</div>